### ISSUE TITLE
cross build

### ISSUE THREAD

**Issue by palanga** [palanga/zio-cassandra#29]
Cross build for:
- [x] 3.*
- [x] 2.13.*
- [ ] ~2.12.*~ (we wont target this version for now)

**Comment by palanga** [comment]
@mariohuizar There's an older version for 2.13. But I'm planning to cross build the latest.

**Comment by palanga** [comment]
@mariohuizar publishing for scala 2.13 done. Can you try with version 0.10.0 ?

`libraryDependencies += "io.github.palanga" %% "zio-cassandra" % "v0.10.0"`

Please let me know if you encounter any problems.

**Comment by mariohuizar** [comment]
Awsome, thanks for the cross build. Will give it a try.
